# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_H_cpp <- function(X, M, y, delta, W, H) {
    invisible(.Call(`_coxNMF_update_H_cpp`, X, M, y, delta, W, H))
}

update_W_cpp <- function(X, M, y, delta, W, H, beta, alpha) {
    invisible(.Call(`_coxNMF_update_W_cpp`, X, M, y, delta, W, H, beta, alpha))
}

#' @export
calc_surv_loss <- function(X, M, y, delta, W, beta) {
    .Call(`_coxNMF_calc_surv_loss`, X, M, y, delta, W, beta)
}

#' @export
calc_loss_cpp <- function(X, M, y, delta, W, H, beta, alpha, lambda, eta) {
    .Call(`_coxNMF_calc_loss_cpp`, X, M, y, delta, W, H, beta, alpha, lambda, eta)
}

cdfit_cox_dh <- function(X, d, lambda, eps, max_iter, gamma, m, alpha, dfmax, user, warn) {
    .Call(`_coxNMF_cdfit_cox_dh`, X, d, lambda, eps, max_iter, gamma, m, alpha, dfmax, user, warn)
}

cdfit_cox_dh_one_lambda <- function(X, d, lambda, eps, max_iter, m, alpha) {
    .Call(`_coxNMF_cdfit_cox_dh_one_lambda`, X, d, lambda, eps, max_iter, m, alpha)
}

cdfit_cox_dh_one_lambda_it <- function(X, d, lambda, a, m, alpha, it) {
    .Call(`_coxNMF_cdfit_cox_dh_one_lambda_it`, X, d, lambda, a, m, alpha, it)
}

update_beta_cpp <- function(X, y, alpha, lambda, beta0, it) {
    .Call(`_coxNMF_update_beta_cpp`, X, y, alpha, lambda, beta0, it)
}

#' @export
standardize <- function(W, H, beta) {
    invisible(.Call(`_coxNMF_standardize`, W, H, beta))
}

#' @export
optimize_loss_cpp <- function(X, M, y, delta, W0, H0, beta0, alpha, lambda, eta, tol, maxit, verbose, init) {
    .Call(`_coxNMF_optimize_loss_cpp`, X, M, y, delta, W0, H0, beta0, alpha, lambda, eta, tol, maxit, verbose, init)
}

