# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_H_cpp <- function(X, M, W, beta, H, y, delta, alpha, WtX) {
    .Call(`_coxNMF_update_H_cpp`, X, M, W, beta, H, y, delta, alpha, WtX)
}

